version: '2.1'
services:
  localstack:
    image: localstack/localstack:0.13.0
    container_name: ${LOCALSTACK_DOCKER_NAME:-localstack_main}
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY:- }
      - DNS_ADDRESS=0
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "./bin:/docker-entrypoint-initaws.d"
      - "./lambda:/tmp/lambda"
